version: '3.7'

services:
  neo4j:
    #image: neo4j:4.2.3-enterprise
    #image: neo4j:5.2.0-enterprise
    image: neo4j:5.2.0-community #https://hub.docker.com/_/neo4j
    container_name: neo4j
    hostname: neo4j
    # volumes:
    #   - $HOME/graph_data/my_data:/data
    #   - $HOME/graph_data/my_data:/var/lib/neo4j/import
    # volumes:
      # - ./plugins:/plugins
      # - ./data:/data
      # - ./import:/var/lib/neo4j/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${NEO4J_USER_NAME}/${NEO4J_PASSWD}
      - NEO4J_PLUGINS=["apoc", "n10s", "graph-data-science"]
      #- NEO4J_PLUGINS=["apoc", "n10s"]
      #- NEO4J_PLUGINS=["apoc"]
      - apoc.import.file.enabled=true
      - apoc.export.file.enabled=true
      - apoc.export.json.all=true
      # Comment these lines if you do not have the memory available
      # - NEO4J_dbms_memory_pagecache_size=4G
      # - NEO4j_dbms_memory_heap_initial__size=4G
      # - NEO4J_dbms_memory_heap_max__size=8G
    networks:
      - neo_net
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyterlab
    hostname: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    links:
      - neo4j
    networks:
      - neo_net
    # user: root
    # #working_dir: /home/$USER
    environment:
      - NB_USER=$USER
      - NB_GROUP=$GROUP
      - NB_UID=$UID
      - NB_GID=$GID
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS= -R
    #   - GRANT_SUDO=yes
    #   - DOCKER_STACKS_JUPYTER_CMD=lab
      - JUPYTER_TOKEN=docker
      # - JUPYTER_ENABLE_LAB=yes
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER_NAME=${NEO4J_USER_NAME} #from .env file
      - NEO4J_PASSWD=${NEO4J_PASSWD} #from .env file
    depends_on: 
      neo4j:
        condition: service_healthy #https://github.com/neo4j/neo4j/issues/7203

networks:
  neo_net:    

